il_castello/config/routes.rb
Rails.application.routes.draw do

  resources :showcars
  devise_for :users
  devise_for :clients
  resources :templates




  root 'welcome#index'

  get 'servicios/' => 'templates#servicios', as: :servicios
  get 'conocenos/' => 'templates#conocenos', as: :conocenos
  get 'contactanos/' => 'templates#contactanos', as: :contactanos
  get 'CMS/' => 'templates#CMS', as: :CMS
  get 'profile/' => "users#profile"







end

il_castello/app/views/partials/_cars_view.html.erb
  <section class="wrapper style1">
          <div class="container">
              <div class="row">
                   <% @showcars.each do |showc| %>
                        <section class="6u 12u(narrower)" style="border: solid 3px;border-style: groove;border-radius: 15px; margin-left: 2%;">
                            <div class="box post">
                              <%= link_to image_tag("showcar/" << showc.photo_link), root_path, :class  => "image left" %>
                                <div class="inner" style="margin-left: 52%;">
                                    <h3><%= showc.name %></h3>
                                    <p><%= showc.description%></p>
                                 </div>
                            </div>
                          </section>

                      <%end%>
                  </div>
              </div>

il_castello/app/views/partials/_cms_showcar.html.erb
<p id="notice"><%= notice %></p>
<div class="inner-cms">

  <h1 class="cms-h1">Listing Showcar</h1>
  <div class="row">


        <div class="col-md-1">Name</div>
        <div class="col-md-7">Description</div>
        <div class="col-md-1">Photo link</div>
        <div class="col-md-3"></div>
    </div>

    <br>

      <% @showcars.each do |showcar| %>

        <div class="row">
          <div class="col-md-1"><%= showcar.name %></div>
          <div class="col-md-7"><%= showcar.description %></div>
          <div class="col-md-1"><%= showcar.photo_link %></div>
          <div class="col-md-3">
            <div class="row">
            <div class="col-md-4"><%= link_to 'Show', showcar , class: "show-button"%></div>
            <div class="col-md-4"><%= link_to 'Edit', edit_showcar_path(showcar), class: "edit-button" %></div>
            <div class="col-md-4"><%= link_to 'Destroy', showcar, method: :delete, data: { confirm: 'Are you sure?' }, class: "destroy-button" %></div>
              </div>
          </div>
        </div>
        <hr>
      <% end %>

<br>
      <div class="">
          <%= link_to 'New Showcar', new_showcar_path, class: "newshowcar-button" %>
      </div>
  </div>

<br>

il_castello/app/views/partials/_cms_views.html.erb
<p id="notice"><%= notice %></p>
<div class="inner-cms">

  <h1 class="cms-h1">Listing Views</h1>
  <div class="row">


        <div class="col-md-1">Title</div>
        <div class="col-md-7">Content</div>
        <div class="col-md-1">UrlImage</div>
        <div class="col-md-3"></div>
    </div>

    <br>

    <% @templates.each do |template| %>

        <div class="row">
              <div class="col-md-1"><%= template.title %></div>
              <div class="col-md-7">  <%= template.content %></div>
              <div class="col-md-1"><%= template.urlImage %></div>
              <div class="col-md-3">
                  <div class="row">
                    <div class="col-md-4"><%= link_to 'Show', template %></div>
                    <div class="col-md-4"><%= link_to 'Edit', edit_template_path(template) %></div>
                    <div class="col-md-4"><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></div>
                  </div>
              </div>
        </div>
        <hr>
    <% end %>


    <br>
          <div class="">
              <%= link_to 'New Template', new_template_path, class: "newshowcar-button" %>
          </div>
      </div>

    <br>

il_castello/app/views/partials/_session.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if !user_signed_in? %>
    <li><<span class="glyphicon glyphicon-user"></span> <%= link_to "Sign Up", new_user_registration_path %> </li>
    <li><span class="glyphicon glyphicon-log-in"></span> <%= link_to "Log In", new_user_session_path %> </li>
    <%else%>

    <li><%= link_to current_user.name, profile_path, :style=>"border-bottom:black"%> </li>
    <!--
    <li><span class="glyphicon glyphicon-user"></span> Saludos, <%= current_user.name %></li>-->
    <li><span class="glyphicon glyphicon-log-in"></span> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li
  <%end%>
</ul>